#!/bin/bash
# combustion: network
# Redirect output to the console
exec > >(exec tee -a /dev/tty0) 2>&1

## Set hostname
hostnamectl set-hostname server

## Copy config to /boot/efi
cp extraconfig.txt /boot/efi/

## Setup vconsole so framebuffer console has right font/keyboard layout (Optional)
cp vconsole.conf /etc/vconsole.conf

## Disable IPv6
cp 90-disableipv6.conf /etc/sysctl.d/

## Enable i2c on boot
cp 10-i2c.conf /etc/modules-load.d/

## Install build environment for argon one deamon
zypper --non-interactive install gcc dtc linux-headers make git toolbox i2c-tools

## Mount /var and /home so user can be created smoothly
mount /var
mount /home

## Make user
useradd -m server
echo 'server:$6$vm5gwdfLRGRIQYM2$r09/8tP.KFnDzRjUjqSAzDjhZgbkThVZq5u1I3Wn0voLd4fDHwvj9/19ZbVR20h7u7eLx.lG89dLzLIUvRZwZ1' | chpasswd -e

## Add user to sudoers
echo "server ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/server

## Create ssh folder and populate authorized_keys for remote sshd
mkdir -pm700 /home/server/.ssh
chown server:users -R /home/server/.ssh
cat server.pub >> /home/server/.ssh/authorized_keys
systemctl enable sshd.service

## Reboot after setup
cp firstbootreboot.service /etc/systemd/system/
systemctl enable firstbootreboot.service

## Clear up mounts
umount /var
umount /home